<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-03-14 17:18

$extensionPath = t3lib_extMgm::extPath('ics_sit_query');
return array(
	'tx_icssitquery_debug' => $extensionPath . 'Classes/class.tx_icssitquery_Debug.php',
	'tx_icssitquery_ifilter' => $extensionPath . 'Classes/interface.tx_icssitquery_IFilter.php',
	'tx_icssitquery_iquery' => $extensionPath . 'Classes/interface.tx_icssitquery_IQuery.php',
	'tx_icssitquery_iqueryservice' => $extensionPath . 'Classes/interface.tx_icssitquery_IQueryService.php',
	'tx_icssitquery_isortingprovider' => $extensionPath . 'Classes/interface.tx_icssitquery_ISortingProvider.php',
	'tx_icssitquery_itostring' => $extensionPath . 'Classes/interface.tx_icssitquery_IToString.php',
	'tx_icssitquery_itostringconf' => $extensionPath . 'Classes/interface.tx_icssitquery_IToStringConf.php',
	'tx_icssitquery_itostringobj' => $extensionPath . 'Classes/interface.tx_icssitquery_IToStringObj.php',
	'tx_icssitquery_itostringobjconf' => $extensionPath . 'Classes/interface.tx_icssitquery_IToStringObjConf.php',
	'tx_icssitquery_abstractaccomodation' => $extensionPath . 'Classes/data/class.tx_icssitquery_AbstractAccomodation.php',
	'tx_icssitquery_abstractdata' => $extensionPath . 'Classes/data/class.tx_icssitquery_AbstractData.php',
	'tx_icssitquery_abstractevent' => $extensionPath . 'Classes/data/class.tx_icssitquery_AbstractEvent.php',
	'tx_icssitquery_abstractrestaurant' => $extensionPath . 'Classes/data/class.tx_icssitquery_AbstractRestaurant.php',
	'tx_icssitquery_address' => $extensionPath . 'Classes/data/class.tx_icssitquery_Address.php',
	'tx_icssitquery_coordinates' => $extensionPath . 'Classes/data/class.tx_icssitquery_Coordinates.php',
	'tx_icssitquery_link' => $extensionPath . 'Classes/data/class.tx_icssitquery_Link.php',
	'tx_icssitquery_name' => $extensionPath . 'Classes/data/class.tx_icssitquery_Name.php',
	'tx_icssitquery_phone' => $extensionPath . 'Classes/data/class.tx_icssitquery_Phone.php',
	'tx_icssitquery_picture' => $extensionPath . 'Classes/data/class.tx_icssitquery_Picture.php',
);
?>